services:
  mongo-service:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' --quiet"]
      interval: 5s
      retries: 5
      start_period: 10s
    ports:
      - "27017:27017"

  backend-service:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:8080"
    depends_on:
      mongo-service:
        condition: service_healthy

  frontend-service:
    container_name: frontend
    build: ./frontend
    env_file:
      - ./frontend/.env.docker
    ports:
      - "80:80"
    
volumes:
  mongo_data:
