apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: monitoring
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - wanderlust
  endpoints:
  - port: http
    path: /metrics
    interval: 15s