apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-monitor
  namespace: monitoring
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  namespaceSelector:
    matchNames: 
      - wanderlust
  endpoints:
  - port: http
    path: /metrics
    interval: 15s