apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: wanderlust
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongo-storage
  volumeMode: Filesystem
  resources:
    requests:
      storage: 4Gi
